/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectfinaljava;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JWindow;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Florin
 */
public class Interfata extends javax.swing.JFrame {
    CarteDeTelefon agenda;
    public Interfata() {
        initComponents();
        jMenuItemOpen.setEnabled(false);
        jMenuItemSave.setEnabled(false);
        agenda = new CarteDeTelefon();
        jTable.setModel(agenda);
        jTable.setAutoCreateRowSorter(true);
        TimerTask task1 = new TimerTask(){
            public void run(){
                lReclama.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\Reclame\\1.png"));
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        TimerTask task2 = new TimerTask(){
            public void run(){
                lReclama.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\Reclame\\2.jpg"));
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        TimerTask task3 = new TimerTask(){
            public void run(){
                lReclama.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\Reclame\\6.png"));
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        TimerTask task4 = new TimerTask(){
            public void run(){
                lReclama.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\Reclame\\4.jpg"));
                try {
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        Timer t = new Timer();
        t.schedule(task1,0,5000);
        t.schedule(task2,5000,5000);
        t.schedule(task3,5000,5000);
        t.schedule(task4,5000,5000);
        
        jMenuItemOpen.setMnemonic('O');
        jMenuItemSave.setMnemonic('S');
        KeyStroke openKeyStroke = KeyStroke.getKeyStroke("control O");
        jMenuItemOpen.setAccelerator(openKeyStroke);
        KeyStroke saveKeyStroke = KeyStroke.getKeyStroke("control S");
        jMenuItemSave.setAccelerator(saveKeyStroke);
        KeyStroke exitKeyStroke = KeyStroke.getKeyStroke("control E");
        jMenuItemIesire.setAccelerator(exitKeyStroke);
        KeyStroke keyStrokeToSterge= KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, KeyEvent.CTRL_DOWN_MASK);
        jMenuItemSterge.setAccelerator(keyStrokeToSterge);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jdModifica = new javax.swing.JDialog();
        ld2NrTel = new javax.swing.JLabel();
        ld2Nume = new javax.swing.JLabel();
        ld2Cnp = new javax.swing.JLabel();
        ld2Prenume = new javax.swing.JLabel();
        tfd2Cnp = new javax.swing.JTextField();
        tfd2NrTel = new javax.swing.JTextField();
        tfd2Nume = new javax.swing.JTextField();
        tfd2Prenume = new javax.swing.JTextField();
        bd2Modifica = new javax.swing.JButton();
        bd2Anulare = new javax.swing.JButton();
        jdFiltreaza = new javax.swing.JDialog();
        ld3NrTel = new javax.swing.JLabel();
        ld3Nume = new javax.swing.JLabel();
        ld3Cnp = new javax.swing.JLabel();
        ld3Prenume = new javax.swing.JLabel();
        tfd3Cnp = new javax.swing.JTextField();
        tfd3NrTel = new javax.swing.JTextField();
        tfd3Nume = new javax.swing.JTextField();
        tfd3Prenume = new javax.swing.JTextField();
        bd3Filtreaza = new javax.swing.JButton();
        bd3Anulare = new javax.swing.JButton();
        jdSortare = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonNume = new javax.swing.JRadioButton();
        jRadioButtonPrenume = new javax.swing.JRadioButton();
        jRadioButtonCnp = new javax.swing.JRadioButton();
        jRadioButtonNrTel = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonCrescator = new javax.swing.JRadioButton();
        jRadioButtonDescrescator = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jOptionPaneInregistrare = new javax.swing.JOptionPane();
        jOptionPaneParola = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jOptionPaneIesire = new javax.swing.JOptionPane();
        jOptionPaneSterge = new javax.swing.JOptionPane();
        jdCauta = new javax.swing.JDialog();
        ld3NrTel1 = new javax.swing.JLabel();
        ld3Nume1 = new javax.swing.JLabel();
        ld3Cnp1 = new javax.swing.JLabel();
        ld3Prenume1 = new javax.swing.JLabel();
        tfd3Cnp1 = new javax.swing.JTextField();
        tfd3NrTel1 = new javax.swing.JTextField();
        tfd3Nume1 = new javax.swing.JTextField();
        tfd3Prenume1 = new javax.swing.JTextField();
        bd3Filtreaza1 = new javax.swing.JButton();
        bd3Anulare1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        lReclama = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lPrenume = new javax.swing.JLabel();
        lNume = new javax.swing.JLabel();
        lCnp = new javax.swing.JLabel();
        lNrTel = new javax.swing.JLabel();
        ftNume = new javax.swing.JFormattedTextField();
        ftPrenume = new javax.swing.JFormattedTextField();
        ftCnp = new javax.swing.JFormattedTextField();
        ftNrTel = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        bAdauga = new javax.swing.JButton();
        bSterge = new javax.swing.JButton();
        bFiltrare = new javax.swing.JButton();
        bCauta = new javax.swing.JButton();
        bModifica = new javax.swing.JButton();
        bSortare = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemIesire = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItemSterge = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();

        jdModifica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdModifica.setLocation(new java.awt.Point(300, 300));
        jdModifica.setMinimumSize(new java.awt.Dimension(300, 300));
        jdModifica.setModal(true);
        jdModifica.setResizable(false);

        ld2NrTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld2NrTel.setText("NrTel");
        ld2NrTel.setMaximumSize(new java.awt.Dimension(27, 14));
        ld2NrTel.setMinimumSize(new java.awt.Dimension(27, 14));

        ld2Nume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld2Nume.setText("Nume");

        ld2Cnp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld2Cnp.setText("CNP");
        ld2Cnp.setMaximumSize(new java.awt.Dimension(27, 14));
        ld2Cnp.setMinimumSize(new java.awt.Dimension(27, 14));

        ld2Prenume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld2Prenume.setText("Prenume");
        ld2Prenume.setMaximumSize(new java.awt.Dimension(27, 14));
        ld2Prenume.setMinimumSize(new java.awt.Dimension(27, 14));

        tfd2Cnp.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd2Cnp.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfd2NrTel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd2NrTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd2NrTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd2NrTelActionPerformed(evt);
            }
        });

        tfd2Nume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd2Nume.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfd2Prenume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd2Prenume.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        bd2Modifica.setText("Modifica");
        bd2Modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd2ModificaActionPerformed(evt);
            }
        });

        bd2Anulare.setText("Anulare");
        bd2Anulare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd2AnulareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdModificaLayout = new javax.swing.GroupLayout(jdModifica.getContentPane());
        jdModifica.getContentPane().setLayout(jdModificaLayout);
        jdModificaLayout.setHorizontalGroup(
            jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdModificaLayout.createSequentialGroup()
                        .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdModificaLayout.createSequentialGroup()
                                .addComponent(ld2NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd2NrTel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(jdModificaLayout.createSequentialGroup()
                                .addComponent(ld2Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd2Cnp))
                            .addGroup(jdModificaLayout.createSequentialGroup()
                                .addComponent(ld2Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd2Nume))
                            .addGroup(jdModificaLayout.createSequentialGroup()
                                .addComponent(ld2Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd2Prenume)))
                        .addGap(10, 10, 10))
                    .addGroup(jdModificaLayout.createSequentialGroup()
                        .addComponent(bd2Modifica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bd2Anulare)
                        .addContainerGap())))
        );
        jdModificaLayout.setVerticalGroup(
            jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdModificaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd2Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd2Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd2Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld2NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd2NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jdModificaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bd2Modifica)
                    .addComponent(bd2Anulare))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdFiltreaza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdFiltreaza.setLocation(new java.awt.Point(300, 300));
        jdFiltreaza.setMinimumSize(new java.awt.Dimension(300, 300));
        jdFiltreaza.setModal(true);
        jdFiltreaza.setResizable(false);

        ld3NrTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3NrTel.setText("NrTel");
        ld3NrTel.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3NrTel.setMinimumSize(new java.awt.Dimension(27, 14));

        ld3Nume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Nume.setText("Nume");

        ld3Cnp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Cnp.setText("CNP");
        ld3Cnp.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3Cnp.setMinimumSize(new java.awt.Dimension(27, 14));

        ld3Prenume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Prenume.setText("Prenume");
        ld3Prenume.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3Prenume.setMinimumSize(new java.awt.Dimension(27, 14));

        tfd3Cnp.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Cnp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3Cnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3CnpActionPerformed(evt);
            }
        });

        tfd3NrTel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3NrTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3NrTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3NrTelActionPerformed(evt);
            }
        });

        tfd3Nume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Nume.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfd3Prenume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Prenume.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3Prenume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3PrenumeActionPerformed(evt);
            }
        });

        bd3Filtreaza.setText("Filtreaza");
        bd3Filtreaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd3FiltreazaActionPerformed(evt);
            }
        });

        bd3Anulare.setText("Anulare");
        bd3Anulare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd3AnulareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdFiltreazaLayout = new javax.swing.GroupLayout(jdFiltreaza.getContentPane());
        jdFiltreaza.getContentPane().setLayout(jdFiltreazaLayout);
        jdFiltreazaLayout.setHorizontalGroup(
            jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdFiltreazaLayout.createSequentialGroup()
                        .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                                .addComponent(ld3NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3NrTel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                                .addComponent(ld3Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Cnp))
                            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                                .addComponent(ld3Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Nume))
                            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                                .addComponent(ld3Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Prenume)))
                        .addGap(10, 10, 10))
                    .addGroup(jdFiltreazaLayout.createSequentialGroup()
                        .addComponent(bd3Filtreaza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bd3Anulare)
                        .addContainerGap())))
        );
        jdFiltreazaLayout.setVerticalGroup(
            jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdFiltreazaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Nume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Cnp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3NrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jdFiltreazaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bd3Filtreaza)
                    .addComponent(bd3Anulare))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdSortare.setLocation(new java.awt.Point(300, 300));
        jdSortare.setMinimumSize(new java.awt.Dimension(364, 300));
        jdSortare.setModal(true);
        jdSortare.setResizable(false);

        jLabel1.setText("Sortare dupa:");

        buttonGroup1.add(jRadioButtonNume);
        jRadioButtonNume.setText("nume");

        buttonGroup1.add(jRadioButtonPrenume);
        jRadioButtonPrenume.setText("prenume");

        buttonGroup1.add(jRadioButtonCnp);
        jRadioButtonCnp.setText("CNP");

        buttonGroup1.add(jRadioButtonNrTel);
        jRadioButtonNrTel.setText("numar de telefon");
        jRadioButtonNrTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNrTelActionPerformed(evt);
            }
        });

        jLabel2.setText("Sortare:");

        buttonGroup2.add(jRadioButtonCrescator);
        jRadioButtonCrescator.setText("crescatoare");

        buttonGroup2.add(jRadioButtonDescrescator);
        jRadioButtonDescrescator.setText("descrescatoare");

        jButton1.setText("Sortare");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Anulare");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdSortareLayout = new javax.swing.GroupLayout(jdSortare.getContentPane());
        jdSortare.getContentPane().setLayout(jdSortareLayout);
        jdSortareLayout.setHorizontalGroup(
            jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdSortareLayout.createSequentialGroup()
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdSortareLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jdSortareLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jRadioButtonNume)
                            .addComponent(jRadioButtonPrenume)
                            .addComponent(jRadioButtonCnp)
                            .addComponent(jRadioButtonNrTel))))
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdSortareLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCrescator)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonDescrescator)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdSortareLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jdSortareLayout.setVerticalGroup(
            jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdSortareLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCrescator)
                    .addComponent(jRadioButtonNume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDescrescator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCnp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNrTel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jdSortareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(48, 48, 48))
        );

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        jFrame1.setMinimumSize(new java.awt.Dimension(200, 200));
        jFrame1.setResizable(false);
        jFrame1.setSize(new java.awt.Dimension(200, 200));

        jTextPane1.setText("Proiect final InfoAcademy\nLazar Florin-Cristian");
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
        );

        jdCauta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jdCauta.setLocation(new java.awt.Point(300, 300));
        jdCauta.setMinimumSize(new java.awt.Dimension(300, 300));
        jdCauta.setModal(true);
        jdCauta.setResizable(false);

        ld3NrTel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3NrTel1.setText("NrTel");
        ld3NrTel1.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3NrTel1.setMinimumSize(new java.awt.Dimension(27, 14));

        ld3Nume1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Nume1.setText("Nume");

        ld3Cnp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Cnp1.setText("CNP");
        ld3Cnp1.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3Cnp1.setMinimumSize(new java.awt.Dimension(27, 14));

        ld3Prenume1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ld3Prenume1.setText("Prenume");
        ld3Prenume1.setMaximumSize(new java.awt.Dimension(27, 14));
        ld3Prenume1.setMinimumSize(new java.awt.Dimension(27, 14));

        tfd3Cnp1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Cnp1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3Cnp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3Cnp1ActionPerformed(evt);
            }
        });

        tfd3NrTel1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3NrTel1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3NrTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3NrTel1ActionPerformed(evt);
            }
        });

        tfd3Nume1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Nume1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfd3Prenume1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tfd3Prenume1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfd3Prenume1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd3Prenume1ActionPerformed(evt);
            }
        });

        bd3Filtreaza1.setText("Cauta");
        bd3Filtreaza1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd3Filtreaza1ActionPerformed(evt);
            }
        });

        bd3Anulare1.setText("Anulare");
        bd3Anulare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bd3Anulare1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdCautaLayout = new javax.swing.GroupLayout(jdCauta.getContentPane());
        jdCauta.getContentPane().setLayout(jdCautaLayout);
        jdCautaLayout.setHorizontalGroup(
            jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCautaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCautaLayout.createSequentialGroup()
                        .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdCautaLayout.createSequentialGroup()
                                .addComponent(ld3NrTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3NrTel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                            .addGroup(jdCautaLayout.createSequentialGroup()
                                .addComponent(ld3Cnp1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Cnp1))
                            .addGroup(jdCautaLayout.createSequentialGroup()
                                .addComponent(ld3Nume1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Nume1))
                            .addGroup(jdCautaLayout.createSequentialGroup()
                                .addComponent(ld3Prenume1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfd3Prenume1)))
                        .addGap(10, 10, 10))
                    .addGroup(jdCautaLayout.createSequentialGroup()
                        .addComponent(bd3Filtreaza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bd3Anulare1)
                        .addContainerGap())))
        );
        jdCautaLayout.setVerticalGroup(
            jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCautaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Nume1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Nume1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Prenume1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Prenume1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3Cnp1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3Cnp1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ld3NrTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfd3NrTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jdCautaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bd3Filtreaza1)
                    .addComponent(bd3Anulare1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 150));
        setMinimumSize(new java.awt.Dimension(600, 420));
        setPreferredSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nume", "Prenume", "CNP", "NrTel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 518;
        gridBagConstraints.ipady = 299;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        lReclama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lReclama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lReclama.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lReclama.setMaximumSize(new java.awt.Dimension(40, 20));
        lReclama.setMinimumSize(new java.awt.Dimension(40, 20));
        lReclama.setName(""); // NOI18N
        lReclama.setPreferredSize(new java.awt.Dimension(40, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 751;
        gridBagConstraints.ipady = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(lReclama, gridBagConstraints);

        lPrenume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lPrenume.setText("Prenume");

        lNume.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNume.setText("Nume");
        lNume.setToolTipText("");
        lNume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lNumeMouseEntered(evt);
            }
        });
        lNume.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lNumeKeyPressed(evt);
            }
        });

        lCnp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCnp.setText("CNP");

        lNrTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNrTel.setText("NrTel");

        ftNume.setForeground(new java.awt.Color(153, 153, 153));
        ftNume.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftNume.setText("Introduceti text");
        ftNume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ftNume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftNumeFocusGained(evt);
            }
        });
        ftNume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftNumeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ftNumeMouseEntered(evt);
            }
        });

        ftPrenume.setForeground(new java.awt.Color(153, 153, 153));
        ftPrenume.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftPrenume.setText("Introduceti text");
        ftPrenume.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ftPrenume.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftPrenumeFocusGained(evt);
            }
        });
        ftPrenume.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftPrenumeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ftPrenumeMouseEntered(evt);
            }
        });

        ftCnp.setForeground(new java.awt.Color(153, 153, 153));
        ftCnp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftCnp.setText("Introduceti text");
        ftCnp.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ftCnp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftCnpFocusGained(evt);
            }
        });
        ftCnp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftCnpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ftCnpMouseEntered(evt);
            }
        });

        ftNrTel.setForeground(new java.awt.Color(153, 153, 153));
        ftNrTel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ftNrTel.setText("Introduceti text");
        ftNrTel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ftNrTel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ftNrTelFocusGained(evt);
            }
        });
        ftNrTel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftNrTelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ftNrTelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNrTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lCnp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lPrenume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lNume, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftNume, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftNrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftCnp, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftPrenume, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lNume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftNume, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftPrenume, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lCnp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ftCnp, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lNrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftNrTel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 162;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bAdauga.setText("Adauga");
        bAdauga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAdaugaMouseEntered(evt);
            }
        });
        bAdauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAdaugaActionPerformed(evt);
            }
        });
        bAdauga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bAdaugaKeyPressed(evt);
            }
        });
        jPanel2.add(bAdauga);

        bSterge.setText("Sterge");
        bSterge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bStergeMouseEntered(evt);
            }
        });
        bSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStergeActionPerformed(evt);
            }
        });
        jPanel2.add(bSterge);

        bFiltrare.setText("Filtreaza");
        bFiltrare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bFiltrareMouseEntered(evt);
            }
        });
        bFiltrare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFiltrareActionPerformed(evt);
            }
        });
        jPanel2.add(bFiltrare);

        bCauta.setText("Cauta");
        bCauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCautaActionPerformed(evt);
            }
        });
        jPanel2.add(bCauta);

        bModifica.setText("Modifica");
        bModifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bModificaMouseEntered(evt);
            }
        });
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });
        jPanel2.add(bModifica);

        bSortare.setText("Sortare");
        bSortare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSortareMouseEntered(evt);
            }
        });
        bSortare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSortareActionPerformed(evt);
            }
        });
        jPanel2.add(bSortare);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 509;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        jMenu1.setText("File");
        jMenu1.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu1MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        jMenuItemOpen.setText("Open");
        jMenuItemOpen.setToolTipText("");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setText("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);
        jMenu1.add(jSeparator1);

        jMenuItemIesire.setText("Iesire");
        jMenuItemIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIesireActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemIesire);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Abonati");

        jMenuItem4.setText("Adauga");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Cauta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItemSterge.setText("Sterge");
        jMenuItemSterge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStergeActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemSterge);

        jMenuItem7.setText("Modifica");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        jMenuItem8.setText("Inregistrare");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);
        jMenu4.add(jSeparator2);

        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIesireActionPerformed
        int valoare = jOptionPaneIesire.showConfirmDialog(null, "Doriti sa parasiti aplicatia ?", "Mesaj", JOptionPane.YES_NO_OPTION);
        jOptionPaneIesire.setVisible(true);
        
        if (valoare == jOptionPaneIesire.YES_OPTION) {
            System.exit(0);
        }else if(valoare == jOptionPaneIesire.NO_OPTION){
            jOptionPaneIesire.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItemIesireActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        bAdaugaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStergeActionPerformed
        bStergeActionPerformed(evt);
    }//GEN-LAST:event_jMenuItemStergeActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        jdModifica.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void bFiltrareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFiltrareActionPerformed
        // TODO add your handling code here:
        jdFiltreaza.setVisible(true);
    }//GEN-LAST:event_bFiltrareActionPerformed

    private void bAdaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAdaugaActionPerformed
        try{
            Abonat a = new Abonat(ftNume.getText(),ftPrenume.getText(),ftCnp.getText(),ftNrTel.getText());
            String nume = a.getNume();
            String prenume = a.getPrenume();
            String cnp = a.getCnp();
            String nrTel = a.getNumar();
            
            Object[] row = {nume, prenume, cnp, nrTel};
            
            agenda.addAbonat(a);
            
            
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(
                        this,
                        e.getMessage(),
                        "Eroare!",
                        JOptionPane.ERROR_MESSAGE
                );
            if(null != e.getMessage())switch (e.getMessage()) {
                case "Numele introdus nu este corect!":
                    ftNume.setText("");
                    break;
                case "Prenumele introdus nu este corect!":
                    ftPrenume.setText("");
                    break;
                case "CNP-ul introdus nu este valid.":
                    ftCnp.setText("");
                    break;
                case "Numarul de telefon nu este valid.":
                    ftNrTel.setText("");
                    break;
            }
        }
        
    }//GEN-LAST:event_bAdaugaActionPerformed

    private void ftNumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftNumeMouseClicked
        ftNume.setText("");
    }//GEN-LAST:event_ftNumeMouseClicked

    private void ftPrenumeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPrenumeMouseClicked
        ftPrenume.setText("");
    }//GEN-LAST:event_ftPrenumeMouseClicked

    private void ftCnpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftCnpMouseClicked
        ftCnp.setText("");
    }//GEN-LAST:event_ftCnpMouseClicked

    private void ftNrTelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftNrTelMouseClicked
        ftNrTel.setText("");
    }//GEN-LAST:event_ftNrTelMouseClicked

    private void ftNumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftNumeMouseEntered
        ftNume.setToolTipText("Aici va fi introdus numele abonatului");
    }//GEN-LAST:event_ftNumeMouseEntered

    private void lNumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNumeMouseEntered
        
    }//GEN-LAST:event_lNumeMouseEntered

    private void lNumeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNumeKeyPressed
        
    }//GEN-LAST:event_lNumeKeyPressed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        if(jFileChooser2.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            try {
                try {
                    agenda.incarcareContacte(jFileChooser2.getSelectedFile().getAbsolutePath());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (IOException ex) {
                Logger.getLogger(Interfata.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        // TODO add your handling code here:
        jdModifica.setVisible(true);
    }//GEN-LAST:event_bModificaActionPerformed

    private void bd2AnulareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd2AnulareActionPerformed
        tfd2Nume.setText("");
        tfd2Prenume.setText("");
        tfd2Cnp.setText("");
        tfd2NrTel.setText("");
        jdModifica.setVisible(false);
    
    }//GEN-LAST:event_bd2AnulareActionPerformed

    private void bd3AnulareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd3AnulareActionPerformed
        tfd3Nume.setText("");
        tfd3Prenume.setText("");
        tfd3Cnp.setText("");
        tfd3NrTel.setText("");
        jdFiltreaza.setVisible(false);
    }//GEN-LAST:event_bd3AnulareActionPerformed

    private void tfd3PrenumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3PrenumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3PrenumeActionPerformed

    private void jRadioButtonNrTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNrTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNrTelActionPerformed

    private void bSortareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSortareActionPerformed
        // TODO add your handling code here:
        jdSortare.setVisible(true);
    }//GEN-LAST:event_bSortareActionPerformed

    private void ftNumeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftNumeFocusGained
        
    }//GEN-LAST:event_ftNumeFocusGained

    private void ftPrenumeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftPrenumeFocusGained
        ftPrenume.setText("");
    }//GEN-LAST:event_ftPrenumeFocusGained

    private void ftCnpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftCnpFocusGained
        ftCnp.setText("");
    }//GEN-LAST:event_ftCnpFocusGained

    private void ftNrTelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftNrTelFocusGained
        ftNrTel.setText("");
    }//GEN-LAST:event_ftNrTelFocusGained

    private void bStergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStergeActionPerformed
        
         if(agenda.GetColectie().size()>=1){
            if(jTable.getSelectedRow()==-1){
                
            }
            else
            {int valoare = jOptionPaneSterge.showConfirmDialog(null, "Doriti sa stergeti abonatul ?", "Mesaj", JOptionPane.YES_NO_OPTION);
        jOptionPaneIesire.setVisible(true);
        
        if (valoare == jOptionPaneIesire.YES_OPTION) {
            agenda.removeAbonatAt(jTable.getSelectedRow());
        }else if(valoare == jOptionPaneIesire.NO_OPTION){
            jOptionPaneIesire.setVisible(false);
        }
                }
            
        }
    }//GEN-LAST:event_bStergeActionPerformed

    private void bd3FiltreazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd3FiltreazaActionPerformed
        String nume  = tfd3Nume.getText();
        String prenume = tfd3Prenume.getText();
        String cnp = tfd3Cnp.getText();
        String numar = tfd3NrTel.getText();
        final TableRowSorter<CarteDeTelefon> sorter = new TableRowSorter<CarteDeTelefon>(agenda);
        jTable.setRowSorter(sorter);
        java.util.List<RowFilter<Object,Object>> filters = new ArrayList<RowFilter<Object,Object>>(4);
        filters.add(RowFilter.regexFilter("(?i)" + nume,0));
        filters.add(RowFilter.regexFilter("(?i)" + prenume,1));
        filters.add(RowFilter.regexFilter("(?i)" + cnp,2));
        filters.add(RowFilter.regexFilter("(?i)"+ numar,3));
        RowFilter<Object,Object> serviceFilter = RowFilter.andFilter(filters);
        sorter.setRowFilter(serviceFilter);
    
        
    }//GEN-LAST:event_bd3FiltreazaActionPerformed

    private void ftPrenumeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftPrenumeMouseEntered
        ftPrenume.setToolTipText("Aici va fi introdus prenumele aboatului");
    }//GEN-LAST:event_ftPrenumeMouseEntered

    private void ftCnpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftCnpMouseEntered
        ftCnp.setToolTipText("Aici va fi introdus CNP-ul abonatului");
    }//GEN-LAST:event_ftCnpMouseEntered

    private void ftNrTelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftNrTelMouseEntered
        ftNrTel.setToolTipText("Aici va fi introdus numarul de telefon al abonatului");
    }//GEN-LAST:event_ftNrTelMouseEntered

    private void bAdaugaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAdaugaMouseEntered
        bAdauga.setToolTipText("Prin apasarea acestui buton abonatul va fi adaugat in tabelul");
    }//GEN-LAST:event_bAdaugaMouseEntered

    private void bStergeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStergeMouseEntered
        bSterge.setToolTipText("Prin apasarea acestui buton abonatul selectat va fi sters din tabel");
    }//GEN-LAST:event_bStergeMouseEntered

    private void bFiltrareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bFiltrareMouseEntered
        bFiltrare.setToolTipText("Prin apasarea acestui buton se va deschide o noua fereastra unde veti putea cauta abonatul"
                + " dorit");
    }//GEN-LAST:event_bFiltrareMouseEntered

    private void bModificaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bModificaMouseEntered
        bModifica.setToolTipText("Prin apasarea acestui buton se va deschide o noua fereastra unde veti putea modifica "
                + "datele abonatului selectat");
    }//GEN-LAST:event_bModificaMouseEntered

    private void bSortareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSortareMouseEntered
        bSortare.setToolTipText("Prin apasarea acestui buton se va deschide o noua fereastra unde veti putea sorta abonatii "
                + "din tabel dupa mai multe criterii");
    }//GEN-LAST:event_bSortareMouseEntered

    private void jMenu1MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu1MenuKeyPressed
        
    }//GEN-LAST:event_jMenu1MenuKeyPressed

    private void bAdaugaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bAdaugaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAdaugaKeyPressed

    private void bd2ModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd2ModificaActionPerformed
        String nume = tfd2Nume.getText();
        String prenume = tfd2Prenume.getText();
        String cnp = tfd2Cnp.getText();
        String nrTel = tfd2NrTel.getText();

        agenda.Modificare(jTable.getSelectedRow(), nume, prenume, cnp, nrTel);
    }//GEN-LAST:event_bd2ModificaActionPerformed

    private void tfd2NrTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd2NrTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd2NrTelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jdSortare.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        jdFiltreaza.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //sortare in ordine dupa toate cele 4 butoane pe rand
        if(jRadioButtonNume.isSelected()){
            if(jRadioButtonCrescator.isSelected()){
                agenda.SortareNumeAscendent();
            }else if(jRadioButtonDescrescator.isSelected()){
                agenda.SortareNumeDescendent();
            }
        }
        if(jRadioButtonPrenume.isSelected()){
            if(jRadioButtonCrescator.isSelected()){
                agenda.SortarePrenumeAscendent();
            }else if(jRadioButtonDescrescator.isSelected()){
                agenda.SortarePrenumeDescendent();
            }
        }
        if(jRadioButtonCnp.isSelected()){
            if(jRadioButtonCrescator.isSelected()){
                agenda.SortareCnpAscendent();
            }else if(jRadioButtonDescrescator.isSelected()){
                agenda.SortareCnpDescendent();
            }
        }
        if(jRadioButtonNrTel.isSelected()){
            if(jRadioButtonCrescator.isSelected()){
                agenda.SortareNumarAscendent();
            }else if(jRadioButtonDescrescator.isSelected()){
                agenda.SortareNumarDescendent();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        if(jFileChooser1.showSaveDialog(this)==JFileChooser.APPROVE_OPTION){
            File file = jFileChooser1.getSelectedFile();
            agenda.SalvareLista(file.getAbsolutePath());
            TimerTask task = new TimerTask(){
                public void run(){
                    agenda.SalvareLista(file.getAbsolutePath());
                }
            };
            Timer timer = new Timer();
            timer.schedule(task,0,300000);
        }
        
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void tfd3CnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3CnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3CnpActionPerformed

    private void tfd3NrTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3NrTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3NrTelActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        String parola = jOptionPaneInregistrare.showInputDialog("Introduceti parola");
        
        if((parola !=null)&& (parola.length()>0)){
            if(parola.equals("florin")){
                jMenuItemOpen.setEnabled(true);
                jMenuItemSave.setEnabled(true);
                lReclama.setVisible(false);
            }
            else{
                jOptionPaneParola.showMessageDialog(
                    this,
                    "Parola introdusa nu este corecta",
                    "Eroare!",
                    JOptionPane.ERROR_MESSAGE
                );
            }
            return;
        }else{
            jOptionPaneInregistrare.setVisible(false);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        jFrame1.setLocationRelativeTo(this);
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        if (evt.getClickCount() == 2) {
                jdModifica.setVisible(true);
            }
    }//GEN-LAST:event_jTableMouseClicked

    private void tfd3Cnp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3Cnp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3Cnp1ActionPerformed

    private void tfd3NrTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3NrTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3NrTel1ActionPerformed

    private void tfd3Prenume1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd3Prenume1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfd3Prenume1ActionPerformed

    private void bd3Filtreaza1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd3Filtreaza1ActionPerformed
        String nume = tfd3Nume1.getText();
        String prenume =  tfd3Prenume1.getText();
        String cnp = tfd3Cnp1.getText();
        String numar = tfd3NrTel1.getText();
        
        ListSelectionModel modelSelectie = jTable.getSelectionModel();
        jTable.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTable.setRowSelectionAllowed(true);
        jTable.clearSelection();
        
        int i = agenda.Cautare(nume, prenume, cnp, numar);
        if(i==-1){
            jOptionPane1.setVisible(true);
            JOptionPane.showMessageDialog(null,"Abonatul cautat nu a fost gasit");
        }
        else{
            modelSelectie.setSelectionInterval(i,i);
        }
    }//GEN-LAST:event_bd3Filtreaza1ActionPerformed

    private void bd3Anulare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bd3Anulare1ActionPerformed
        tfd3Nume1.setText("");
        tfd3Prenume1.setText("");
        tfd3Cnp1.setText("");
        tfd3NrTel1.setText("");
        jdCauta.setVisible(false);
    }//GEN-LAST:event_bd3Anulare1ActionPerformed

    private void bCautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCautaActionPerformed
        jdCauta.setVisible(true);
    }//GEN-LAST:event_bCautaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        JWindow window = new JWindow();
        window.getContentPane().add(
            new JLabel("", new ImageIcon(System.getProperty("user.dir")+"\\Reclame\\icon.png"), SwingConstants.CENTER));
        window.setBounds(500, 150, 450, 450);
        window.setVisible(true);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
        }
        window.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interfata().setVisible(true);
            }
        });
        
        
        
        
    }     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAdauga;
    private javax.swing.JButton bCauta;
    private javax.swing.JButton bFiltrare;
    private javax.swing.JButton bModifica;
    private javax.swing.JButton bSortare;
    private javax.swing.JButton bSterge;
    private javax.swing.JButton bd2Anulare;
    private javax.swing.JButton bd2Modifica;
    private javax.swing.JButton bd3Anulare;
    private javax.swing.JButton bd3Anulare1;
    private javax.swing.JButton bd3Filtreaza;
    private javax.swing.JButton bd3Filtreaza1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField ftCnp;
    private javax.swing.JFormattedTextField ftNrTel;
    private javax.swing.JFormattedTextField ftNume;
    private javax.swing.JFormattedTextField ftPrenume;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemIesire;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSterge;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPaneIesire;
    private javax.swing.JOptionPane jOptionPaneInregistrare;
    private javax.swing.JOptionPane jOptionPaneParola;
    private javax.swing.JOptionPane jOptionPaneSterge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonCnp;
    private javax.swing.JRadioButton jRadioButtonCrescator;
    private javax.swing.JRadioButton jRadioButtonDescrescator;
    private javax.swing.JRadioButton jRadioButtonNrTel;
    private javax.swing.JRadioButton jRadioButtonNume;
    private javax.swing.JRadioButton jRadioButtonPrenume;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JDialog jdCauta;
    private javax.swing.JDialog jdFiltreaza;
    private javax.swing.JDialog jdModifica;
    private javax.swing.JDialog jdSortare;
    private javax.swing.JLabel lCnp;
    private javax.swing.JLabel lNrTel;
    private javax.swing.JLabel lNume;
    private javax.swing.JLabel lPrenume;
    private javax.swing.JLabel lReclama;
    private javax.swing.JLabel ld2Cnp;
    private javax.swing.JLabel ld2NrTel;
    private javax.swing.JLabel ld2Nume;
    private javax.swing.JLabel ld2Prenume;
    private javax.swing.JLabel ld3Cnp;
    private javax.swing.JLabel ld3Cnp1;
    private javax.swing.JLabel ld3NrTel;
    private javax.swing.JLabel ld3NrTel1;
    private javax.swing.JLabel ld3Nume;
    private javax.swing.JLabel ld3Nume1;
    private javax.swing.JLabel ld3Prenume;
    private javax.swing.JLabel ld3Prenume1;
    private javax.swing.JTextField tfd2Cnp;
    private javax.swing.JTextField tfd2NrTel;
    private javax.swing.JTextField tfd2Nume;
    private javax.swing.JTextField tfd2Prenume;
    private javax.swing.JTextField tfd3Cnp;
    private javax.swing.JTextField tfd3Cnp1;
    private javax.swing.JTextField tfd3NrTel;
    private javax.swing.JTextField tfd3NrTel1;
    private javax.swing.JTextField tfd3Nume;
    private javax.swing.JTextField tfd3Nume1;
    private javax.swing.JTextField tfd3Prenume;
    private javax.swing.JTextField tfd3Prenume1;
    // End of variables declaration//GEN-END:variables

}